# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'hackdev' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'hackdevTests' do

end

target 'hackdevUITests' do

end

